In [1]:
import pandas as pd

In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/alumnos/taller/env/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/alumnos/taller/env/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 4.9 MB/s eta 0:00:00[31m5.1 MB/s eta 0:00:01
Downloading numpy-2.5.0-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 4.4 MB/s eta 0:00:00m eta 0:00:010:01:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.5.0 pandas-3.0.3

In [2]:
import pandas as pd

In [8]:
lagos = pd.read_csv("lagos_arg.csv")

In [5]:
lagos

,Nombre,Ubicación,Superficie (km²),Profundidad máxima (m),Profundidad media (m),Coordenadas,Sup Tamaño,Latitud en GMS,Longitud en GMS,Latitud en GD,Longitud en GD
0,Lago Argentino,Santa Cruz,1435,500.0,150.0,"50°14'53""S 72°38'43""O",grande,"50°14'53""S","72°38'43""O",-50.248056,-72.645278
1,Lago Viedma,Santa Cruz,1166,NaN,NaN,"49°37'27""S 72°29'42""O",grande,"49°37'27""S","72°29'42""O",-49.624167,-72.495000
2,Lago Nahuel Huapi,Río Negro / Neuquén,540,464.0,157.0,"40°51'16""S 71°36'58""O",grande,"40°51'16""S","71°36'58""O",-40.854444,-71.616111
3,Lago Musters,Chubut,427,39.0,20.0,"45°24'53""S 69°11'52""O",grande,"45°24'53""S","69°11'52""O",-45.414722,-69.197778
4,Lago Cardiel,Santa Cruz,358,NaN,49.0,"48°55'3""S 71°12'53""O",grande,"48°55'3""S","71°12'53""O",-48.917500,-71.214722
5,Lago Epecuén,Buenos Aires,156,11.0,7.0,"37°7'45""S 62°51'53""O",grande,"37°7'45""S","62°51'53""O",-37.129167,-62.864722
6,Lago Pellegrini,Río Negro,116,NaN,NaN,"38°42'25""S 67°58'23""O",grande,"38°42'25""S","67°58'23""O",-38.706944,-67.973056
7,Lago Strobel,Santa Cruz,100,NaN,NaN,"48°25'58""S 71°11'25""O",grande,"48°25'58""S","71°11'25""O",-48.432778,-71.190278
8,Lago Fontana,Chubut,84,NaN,79.0,"44°55'17""S 71°29'45""O",grande,"44°55'17""S","71°29'45""O",-44.921389,-71.495833
9,Lago Huechulafquen,Neuquén,84,NaN,142.0,"39°46'28""S 71°30'32""O",grande,"39°46'28""S","71°30'32""O",-39.774444,-71.508889
10,Lago Traful,Neuquén,78,NaN,NaN,"40°37'50""S 71°24'55""O",grande,"40°37'50""S","71°24'55""O",-40.630556,-71.415278
11,Lago La Plata,Chubut,73,NaN,NaN,"44°51'33""S 71°49'12""O",grande,"44°51'33""S","71°49'12""O",-44.859167,-71.820000
12,Lago Ghío,Santa Cruz,65,NaN,NaN,"47°17'18""S 71°31'49""O",grande,"47°17'18""S","71°31'49""O",-47.288333,-71.530278
13,Lago Menéndez,Chubut,58,287.0,149.0,"42°41'28""S 71°51'45""O",medio,"42°41'28""S","71°51'45""O",-42.691111,-71.862500
14,Lago Aluminé,Neuquén,58,165.0,64.0,"38°55'18""S 71°7'35""O",medio,"38°55'18""S","71°7'35""O",-38.921667,-71.126389
15,Lago Lácar,Neuquén,53,277.0,166.0,"40°9'45""S 71°26'11""O",medio,"40°9'45""S","71°26'11""O",-40.162500,-71.436389
16,Lago Yehuin,"Tierra del Fuego, Antártida e Islas del Atlánt...",49,NaN,43.0,"54°24'43""S 67°42'55""O",medio,"54°24'43""S","67°42'55""O",-54.411944,-67.715278
17,Lago Quiroga,Santa Cruz,47,NaN,NaN,"48°25'1""S 71°33'3""O",medio,"48°25'1""S","71°33'3""O",-48.416944,-71.550833
18,Lago Puelo,Chubut,47,180.0,111.0,"42°9'3""S 71°38'59""O",medio,"42°9'3""S","71°38'59""O",-42.150833,-71.649722
19,Lago Nansen,Santa Cruz,42,NaN,NaN,"47°58'44""S 72°21'11""O",medio,"47°58'44""S","72°21'11""O",-47.978889,-72.353056
20,Lago Belgrano,Santa Cruz,42,NaN,NaN,"47°50'38""S 72°8'34""O",medio,"47°50'38""S","72°8'34""O",-47.843889,-72.142778
21,Lago Futalaufquen,Chubut,42,168.0,101.0,"42°49'42""S 71°40'31""O",medio,"42°49'42""S","71°40'31""O",-42.828333,-71.675278
22,Lago Posadas,Santa Cruz,41,NaN,31.0,"47°29'40""S 71°49'55""O",medio,"47°29'40""S","71°49'55""O",-47.494444,-71.831944
23,Lago Espejo,Neuquén,40,NaN,NaN,"40°40'33""S 71°42'40""O",medio,"40°40'33""S","71°42'40""O",-40.675833,-71.711111
24,Lago Mascardi,Río Negro,39,218.0,111.0,"41°20'46""S 71°32'52""O",medio,"41°20'46""S","71°32'52""O",-41.346111,-71.547778
25,Lago Chepelmut,"Tierra del Fuego, Antártida e Islas del Atlánt...",38,NaN,NaN,"54°23'42""S 67°35'36""O",medio,"54°23'42""S","67°35'36""O",-54.395000,-67.593333
26,Lago Salitroso o Sucio,Santa Cruz,37,NaN,NaN,"47°30'0""S 71°36'48""O",medio,"47°30'0""S","71°36'48""O",-47.500000,-71.613333
27,Lago Lolog,Neuquén,37,NaN,NaN,"40°2'10""S 71°32'11""O",medio,"40°2'10""S","71°32'11""O",-40.036111,-71.536389
28,Lago Tar,Santa Cruz,30,NaN,NaN,"49°13'42""S 72°1'2""O",medio,"49°13'42""S","72°1'2""O",-49.228333,-72.017222
29,Lago Tromen,Neuquén,29,NaN,69.0,"39°31'33""S 71°26'52""O",medio,"39°31'33""S","71°26'52""O",-39.525833,-71.447778
30,Lago Blanco,Chubut,28,NaN,NaN,"45°53'16""S 71°13'25""O",medio,"45°53'16""S","71°13'25""O",-45.887778,-71.223611
31,Lago Quillén,Neuquén,26,NaN,NaN,"39°24'41""S 71°18'52""O",medio,"39°24'41""S","71°18'52""O",-39.411389,-71.314444
32,Lago Asador o Guitarra,Santa Cruz,23,NaN,NaN,"47°51'45""S 71°28'13""O",medio,"47°51'45""S","71°28'13""O",-47.862500,-71.470278
33,Lago Rivadavia,Chubut,23,147.0,104.0,"42°36'39""S 71°39'59""O",medio,"42°36'39""S","71°39'59""O",-42.610833,-71.666389
34,Lago Moquehue,Neuquén,21,NaN,NaN,"38°54'16""S 71°16'26""O",medio,"38°54'16""S","71°16'26""O",-38.904444,-71.273889
35,Lago Correntoso,Neuquén,20,NaN,NaN,"40°42'8""S 71°39'35""O",medio,"40°42'8""S","71°39'35""O",-40.702222,-71.659722
36,Lago Río Chico,Chubut,20,NaN,NaN,"45°35'40""S 68°32'52""O",medio,"45°35'40""S","68°32'52""O",-45.594444,-68.547778
37,Lago Quiroga Chico,Santa Cruz,20,NaN,NaN,"48°29'57""S 71°35'5""O",medio,"48°29'57""S","71°35'5""O",-48.499167,-71.584722
38,Lago Epuyén,Chubut,17,148.0,92.0,"42°11'15""S 71°30'24""O",chico,"42°11'15""S","71°30'24""O",-42.187500,-71.506667
39,Lago Gutiérrez,Río Negro,17,111.0,80.0,"41°12'28""S 71°25'13""O",chico,"41°12'28""S","71°25'13""O",-41.207778,-71.420278
40,Lago Cholila,Chubut,17,108.0,49.0,"42°27'31""S 71°40'9""O",chico,"42°27'31""S","71°40'9""O",-42.458611,-71.669167
41,Lago Paimún,Neuquén,16,NaN,66.0,"39°43'27""S 71°35'2""O",chico,"39°43'27""S","71°35'2""O",-39.724167,-71.583889
42,Lago Azara,Santa Cruz,16,NaN,NaN,"47°50'45""S 72°16'13""O",chico,"47°50'45""S","72°16'13""O",-47.845833,-72.270278
43,Lago Burmeister,Santa Cruz,14,NaN,NaN,"47°57'20""S 72°12'9""O",chico,"47°57'20""S","72°12'9""O",-47.955556,-72.202500
44,Lago Onelli,Santa Cruz,14,NaN,NaN,"50°6'30""S 73°20'59""O",chico,"50°6'30""S","73°20'59""O",-50.108333,-73.349722
45,Lago Meliquina,Neuquén,14,NaN,NaN,"40°19'60""S 71°19'10""O",chico,"40°19'60""S","71°19'10""O",-40.333333,-71.319444
46,Lago Perito Moreno,Río Negro,12,NaN,NaN,"41°3'58""S 71°32'28""O",chico,"41°3'58""S","71°32'28""O",-41.066111,-71.541111
47,Lago Currhué,Neuquén,12,NaN,NaN,"39°50'24""S 71°30'27""O",chico,"39°50'24""S","71°30'27""O",-39.840000,-71.507500
48,Lago Falkner,Neuquén,11,NaN,NaN,"40°29'6""S 71°28'33""O",chico,"40°29'6""S","71°28'33""O",-40.485000,-71.475833
49,Lago Pico Nº 1,Chubut,10,NaN,NaN,"44°14'31""S 71°30'8""O",chico,"44°14'31""S","71°30'8""O",-44.241944,-71.502222
50,Lago Río Bueno,"Tierra del Fuego, Antártida e Islas del Atlánt...",10,NaN,NaN,"54°41'19""S 65°48'23""O",chico,"54°41'19""S","65°48'23""O",-54.688611,-65.806389
51,Lago Rosario,Chubut,10,57.0,25.0,"43°15'36""S 71°20'48""O",chico,"43°15'36""S","71°20'48""O",-43.260000,-71.346667

¿Qué columnas tienen valores categorizados que permiten calcular frecuencias con value_counts?

In [6]:
print(lagos.info())

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Nombre                  52 non-null     str
 1   Ubicación               52 non-null     str
 2   Superficie (km²)        52 non-null     int64
 3   Profundidad máxima (m)  15 non-null     float64
 4   Profundidad media (m)   22 non-null     float64
 5   Coordenadas             52 non-null     str
 6   Sup Tamaño              52 non-null     str
 7   Latitud en GMS          52 non-null     str
 8   Longitud en GMS         52 non-null     str
 9   Latitud en GD           52 non-null     float64
 10  Longitud en GD          52 non-null     float64
dtypes: float64(4), int64(1), str(6)
memory usage: 4.6 KB
None

¿Qué diferencia hay entre las columnas?:

respuesta: coordenadas,  Latitud en GMS y Longitud en GMS son del tipo objeto (object) con datos de tipo GMS mientras que latitud y lng pertenecen al tipo float (float64) con datos de tipos decimales

In [8]:
print(lagos.head())

              Nombre            Ubicación  Superficie (km²)  \
0     Lago Argentino           Santa Cruz              1435
1        Lago Viedma           Santa Cruz              1166
2  Lago Nahuel Huapi  Río Negro / Neuquén               540
3       Lago Musters               Chubut               427
4       Lago Cardiel           Santa Cruz               358

   Profundidad máxima (m)  Profundidad media (m)            Coordenadas  \
0                   500.0                  150.0  50°14'53"S 72°38'43"O
1                     NaN                    NaN  49°37'27"S 72°29'42"O
2                   464.0                  157.0  40°51'16"S 71°36'58"O
3                    39.0                   20.0  45°24'53"S 69°11'52"O
4                     NaN                   49.0   48°55'3"S 71°12'53"O

  Sup Tamaño Latitud en GMS Longitud en GMS  Latitud en GD  Longitud en GD
0     grande     50°14'53"S      72°38'43"O     -50.248056      -72.645278
1     grande     49°37'27"S      72°29'42"O     -49.624167      -72.495000
2     grande     40°51'16"S      71°36'58"O     -40.854444      -71.616111
3     grande     45°24'53"S      69°11'52"O     -45.414722      -69.197778
4     grande      48°55'3"S      71°12'53"O     -48.917500      -71.214722

¿Qué columnas tienen datos faltantes?

respuesta: Los datos decimales de profundidad maxima con resultado NaN en la columna 1 y 4, profundidad media con resultado NaN en columna 1

In [9]:
print(lagos.head())

              Nombre            Ubicación  Superficie (km²)  \
0     Lago Argentino           Santa Cruz              1435
1        Lago Viedma           Santa Cruz              1166
2  Lago Nahuel Huapi  Río Negro / Neuquén               540
3       Lago Musters               Chubut               427
4       Lago Cardiel           Santa Cruz               358

   Profundidad máxima (m)  Profundidad media (m)            Coordenadas  \
0                   500.0                  150.0  50°14'53"S 72°38'43"O
1                     NaN                    NaN  49°37'27"S 72°29'42"O
2                   464.0                  157.0  40°51'16"S 71°36'58"O
3                    39.0                   20.0  45°24'53"S 69°11'52"O
4                     NaN                   49.0   48°55'3"S 71°12'53"O

  Sup Tamaño Latitud en GMS Longitud en GMS  Latitud en GD  Longitud en GD
0     grande     50°14'53"S      72°38'43"O     -50.248056      -72.645278
1     grande     49°37'27"S      72°29'42"O     -49.624167      -72.495000
2     grande     40°51'16"S      71°36'58"O     -40.854444      -71.616111
3     grande     45°24'53"S      69°11'52"O     -45.414722      -69.197778
4     grande      48°55'3"S      71°12'53"O     -48.917500      -71.214722

¿Cuántas filas y columnas tiene el dataset?

Respuesta: filas: 11, columnas: 15

In [10]:
print(lagos.value_counts())

Nombre             Ubicación            Superficie (km²)  Profundidad máxima (m)  Profundidad media (m)  Coordenadas            Sup Tamaño  Latitud en GMS  Longitud en GMS  Latitud en GD  Longitud en GD
Lago Argentino     Santa Cruz           1435              500.0                   150.0                  50°14'53"S 72°38'43"O  grande      50°14'53"S      72°38'43"O       -50.248056     -72.645278        1
Lago Nahuel Huapi  Río Negro / Neuquén  540               464.0                   157.0                  40°51'16"S 71°36'58"O  grande      40°51'16"S      71°36'58"O       -40.854444     -71.616111        1
Lago Musters       Chubut               427               39.0                    20.0                   45°24'53"S 69°11'52"O  grande      45°24'53"S      69°11'52"O       -45.414722     -69.197778        1
Lago Epecuén       Buenos Aires         156               11.0                    7.0                    37°7'45"S 62°51'53"O   grande      37°7'45"S       62°51'53"O       -37.129167     -62.864722        1
Lago Menéndez      Chubut               58                287.0                   149.0                  42°41'28"S 71°51'45"O  medio       42°41'28"S      71°51'45"O       -42.691111     -71.862500        1
Lago Aluminé       Neuquén              58                165.0                   64.0                   38°55'18"S 71°7'35"O   medio       38°55'18"S      71°7'35"O        -38.921667     -71.126389        1
Lago Lácar         Neuquén              53                277.0                   166.0                  40°9'45"S 71°26'11"O   medio       40°9'45"S       71°26'11"O       -40.162500     -71.436389        1
Lago Puelo         Chubut               47                180.0                   111.0                  42°9'3"S 71°38'59"O    medio       42°9'3"S        71°38'59"O       -42.150833     -71.649722        1
Lago Futalaufquen  Chubut               42                168.0                   101.0                  42°49'42"S 71°40'31"O  medio       42°49'42"S      71°40'31"O       -42.828333     -71.675278        1
Lago Mascardi      Río Negro            39                218.0                   111.0                  41°20'46"S 71°32'52"O  medio       41°20'46"S      71°32'52"O       -41.346111     -71.547778        1
Lago Rivadavia     Chubut               23                147.0                   104.0                  42°36'39"S 71°39'59"O  medio       42°36'39"S      71°39'59"O       -42.610833     -71.666389        1
Lago Epuyén        Chubut               17                148.0                   92.0                   42°11'15"S 71°30'24"O  chico       42°11'15"S      71°30'24"O       -42.187500     -71.506667        1
Lago Gutiérrez     Río Negro            17                111.0                   80.0                   41°12'28"S 71°25'13"O  chico       41°12'28"S      71°25'13"O       -41.207778     -71.420278        1
Lago Cholila       Chubut               17                108.0                   49.0                   42°27'31"S 71°40'9"O   chico       42°27'31"S      71°40'9"O        -42.458611     -71.669167        1
Lago Rosario       Chubut               10                57.0                    25.0                   43°15'36"S 71°20'48"O  chico       43°15'36"S      71°20'48"O       -43.260000     -71.346667        1
Name: count, dtype: int64

Cuáles son los nombres de las columnas?

Nombre, Ubicación, Superficie (km²), Profundidad máxima (m),  Profundidad media (m), Coordenadas, Sup Tamaño, Latitud en GMS  Longitud en GMS, lat, lng

In [12]:
print(lagos.value_counts())

Nombre             Ubicación            Superficie (km²)  Profundidad máxima (m)  Profundidad media (m)  Coordenadas            Sup Tamaño  Latitud en GMS  Longitud en GMS  Latitud en GD  Longitud en GD
Lago Argentino     Santa Cruz           1435              500.0                   150.0                  50°14'53"S 72°38'43"O  grande      50°14'53"S      72°38'43"O       -50.248056     -72.645278        1
Lago Nahuel Huapi  Río Negro / Neuquén  540               464.0                   157.0                  40°51'16"S 71°36'58"O  grande      40°51'16"S      71°36'58"O       -40.854444     -71.616111        1
Lago Musters       Chubut               427               39.0                    20.0                   45°24'53"S 69°11'52"O  grande      45°24'53"S      69°11'52"O       -45.414722     -69.197778        1
Lago Epecuén       Buenos Aires         156               11.0                    7.0                    37°7'45"S 62°51'53"O   grande      37°7'45"S       62°51'53"O       -37.129167     -62.864722        1
Lago Menéndez      Chubut               58                287.0                   149.0                  42°41'28"S 71°51'45"O  medio       42°41'28"S      71°51'45"O       -42.691111     -71.862500        1
Lago Aluminé       Neuquén              58                165.0                   64.0                   38°55'18"S 71°7'35"O   medio       38°55'18"S      71°7'35"O        -38.921667     -71.126389        1
Lago Lácar         Neuquén              53                277.0                   166.0                  40°9'45"S 71°26'11"O   medio       40°9'45"S       71°26'11"O       -40.162500     -71.436389        1
Lago Puelo         Chubut               47                180.0                   111.0                  42°9'3"S 71°38'59"O    medio       42°9'3"S        71°38'59"O       -42.150833     -71.649722        1
Lago Futalaufquen  Chubut               42                168.0                   101.0                  42°49'42"S 71°40'31"O  medio       42°49'42"S      71°40'31"O       -42.828333     -71.675278        1
Lago Mascardi      Río Negro            39                218.0                   111.0                  41°20'46"S 71°32'52"O  medio       41°20'46"S      71°32'52"O       -41.346111     -71.547778        1
Lago Rivadavia     Chubut               23                147.0                   104.0                  42°36'39"S 71°39'59"O  medio       42°36'39"S      71°39'59"O       -42.610833     -71.666389        1
Lago Epuyén        Chubut               17                148.0                   92.0                   42°11'15"S 71°30'24"O  chico       42°11'15"S      71°30'24"O       -42.187500     -71.506667        1
Lago Gutiérrez     Río Negro            17                111.0                   80.0                   41°12'28"S 71°25'13"O  chico       41°12'28"S      71°25'13"O       -41.207778     -71.420278        1
Lago Cholila       Chubut               17                108.0                   49.0                   42°27'31"S 71°40'9"O   chico       42°27'31"S      71°40'9"O        -42.458611     -71.669167        1
Lago Rosario       Chubut               10                57.0                    25.0                   43°15'36"S 71°20'48"O  chico       43°15'36"S      71°20'48"O       -43.260000     -71.346667        1
Name: count, dtype: int64

¿Qué tipos de datos tiene cada columna?

Respuesta:
Nombre: object
ubicación: object
Superficie (km²): int
profundidad maxima: float
profundidad media: float
Coordenadas: object
Sup tamaño: object
Latitud en GMS: object
longitud en GMS: object
lat: float
lng: float

In [14]:
print(lagos.info())

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Nombre                  52 non-null     str
 1   Ubicación               52 non-null     str
 2   Superficie (km²)        52 non-null     int64
 3   Profundidad máxima (m)  15 non-null     float64
 4   Profundidad media (m)   22 non-null     float64
 5   Coordenadas             52 non-null     str
 6   Sup Tamaño              52 non-null     str
 7   Latitud en GMS          52 non-null     str
 8   Longitud en GMS         52 non-null     str
 9   Latitud en GD           52 non-null     float64
 10  Longitud en GD          52 non-null     float64
dtypes: float64(4), int64(1), str(6)
memory usage: 4.6 KB
None

Muestra las primeras 5 filas del dataset.

In [15]:
print(lagos.head())

              Nombre            Ubicación  Superficie (km²)  \
0     Lago Argentino           Santa Cruz              1435
1        Lago Viedma           Santa Cruz              1166
2  Lago Nahuel Huapi  Río Negro / Neuquén               540
3       Lago Musters               Chubut               427
4       Lago Cardiel           Santa Cruz               358

   Profundidad máxima (m)  Profundidad media (m)            Coordenadas  \
0                   500.0                  150.0  50°14'53"S 72°38'43"O
1                     NaN                    NaN  49°37'27"S 72°29'42"O
2                   464.0                  157.0  40°51'16"S 71°36'58"O
3                    39.0                   20.0  45°24'53"S 69°11'52"O
4                     NaN                   49.0   48°55'3"S 71°12'53"O

  Sup Tamaño Latitud en GMS Longitud en GMS  Latitud en GD  Longitud en GD
0     grande     50°14'53"S      72°38'43"O     -50.248056      -72.645278
1     grande     49°37'27"S      72°29'42"O     -49.624167      -72.495000
2     grande     40°51'16"S      71°36'58"O     -40.854444      -71.616111
3     grande     45°24'53"S      69°11'52"O     -45.414722      -69.197778
4     grande      48°55'3"S      71°12'53"O     -48.917500      -71.214722

¿Cuántos lagos hay en la provincia de Santa Cruz?

In [16]:
print(lagos["Ubicación"].value_counts())

Ubicación
Santa Cruz                                               16
Neuquén                                                  14
Chubut                                                   13
Río Negro                                                 4
Tierra del Fuego, Antártida e Islas del Atlántico Sur     3
Río Negro / Neuquén                                       1
Buenos Aires                                              1
Name: count, dtype: int64

¿Cuántos lagos hay en cada provincia?

In [17]:
print(lagos["Ubicación"].value_counts())

Ubicación
Santa Cruz                                               16
Neuquén                                                  14
Chubut                                                   13
Río Negro                                                 4
Tierra del Fuego, Antártida e Islas del Atlántico Sur     3
Río Negro / Neuquén                                       1
Buenos Aires                                              1
Name: count, dtype: int64

Crea un gráfico que compare las cantidades de lagos por provincia.

In [24]:
filt = lagos["Ubicación"]
kj = filt.value_counts()
kj
#plotly.bar(data_frame = kj, x = kj.values, y = kj.index, title = "titulo").show()

Ubicación
Santa Cruz                                               16
Neuquén                                                  14
Chubut                                                   13
Río Negro                                                 4
Tierra del Fuego, Antártida e Islas del Atlántico Sur     3
Río Negro / Neuquén                                       1
Buenos Aires                                              1
Name: count, dtype: int64

Filtra los lagos que pertenecen a la provincia de Neuquén. ¿falta algún lago de Nequén en el filtro?

Respuesta: faltan:

Lago Nahuel Huapi  Río Negro

In [9]:

lagos.head(500)

,Nombre,Ubicación,Superficie (km²),Profundidad máxima (m),Profundidad media (m),Coordenadas,Sup Tamaño,Latitud en GMS,Longitud en GMS,Latitud en GD,Longitud en GD
0,Lago Argentino,Santa Cruz,1435,500.0,150.0,"50°14'53""S 72°38'43""O",grande,"50°14'53""S","72°38'43""O",-50.248056,-72.645278
1,Lago Viedma,Santa Cruz,1166,NaN,NaN,"49°37'27""S 72°29'42""O",grande,"49°37'27""S","72°29'42""O",-49.624167,-72.495000
2,Lago Nahuel Huapi,Río Negro / Neuquén,540,464.0,157.0,"40°51'16""S 71°36'58""O",grande,"40°51'16""S","71°36'58""O",-40.854444,-71.616111
3,Lago Musters,Chubut,427,39.0,20.0,"45°24'53""S 69°11'52""O",grande,"45°24'53""S","69°11'52""O",-45.414722,-69.197778
4,Lago Cardiel,Santa Cruz,358,NaN,49.0,"48°55'3""S 71°12'53""O",grande,"48°55'3""S","71°12'53""O",-48.917500,-71.214722
5,Lago Epecuén,Buenos Aires,156,11.0,7.0,"37°7'45""S 62°51'53""O",grande,"37°7'45""S","62°51'53""O",-37.129167,-62.864722
6,Lago Pellegrini,Río Negro,116,NaN,NaN,"38°42'25""S 67°58'23""O",grande,"38°42'25""S","67°58'23""O",-38.706944,-67.973056
7,Lago Strobel,Santa Cruz,100,NaN,NaN,"48°25'58""S 71°11'25""O",grande,"48°25'58""S","71°11'25""O",-48.432778,-71.190278
8,Lago Fontana,Chubut,84,NaN,79.0,"44°55'17""S 71°29'45""O",grande,"44°55'17""S","71°29'45""O",-44.921389,-71.495833
9,Lago Huechulafquen,Neuquén,84,NaN,142.0,"39°46'28""S 71°30'32""O",grande,"39°46'28""S","71°30'32""O",-39.774444,-71.508889
10,Lago Traful,Neuquén,78,NaN,NaN,"40°37'50""S 71°24'55""O",grande,"40°37'50""S","71°24'55""O",-40.630556,-71.415278
11,Lago La Plata,Chubut,73,NaN,NaN,"44°51'33""S 71°49'12""O",grande,"44°51'33""S","71°49'12""O",-44.859167,-71.820000
12,Lago Ghío,Santa Cruz,65,NaN,NaN,"47°17'18""S 71°31'49""O",grande,"47°17'18""S","71°31'49""O",-47.288333,-71.530278
13,Lago Menéndez,Chubut,58,287.0,149.0,"42°41'28""S 71°51'45""O",medio,"42°41'28""S","71°51'45""O",-42.691111,-71.862500
14,Lago Aluminé,Neuquén,58,165.0,64.0,"38°55'18""S 71°7'35""O",medio,"38°55'18""S","71°7'35""O",-38.921667,-71.126389
15,Lago Lácar,Neuquén,53,277.0,166.0,"40°9'45""S 71°26'11""O",medio,"40°9'45""S","71°26'11""O",-40.162500,-71.436389
16,Lago Yehuin,"Tierra del Fuego, Antártida e Islas del Atlánt...",49,NaN,43.0,"54°24'43""S 67°42'55""O",medio,"54°24'43""S","67°42'55""O",-54.411944,-67.715278
17,Lago Quiroga,Santa Cruz,47,NaN,NaN,"48°25'1""S 71°33'3""O",medio,"48°25'1""S","71°33'3""O",-48.416944,-71.550833
18,Lago Puelo,Chubut,47,180.0,111.0,"42°9'3""S 71°38'59""O",medio,"42°9'3""S","71°38'59""O",-42.150833,-71.649722
19,Lago Nansen,Santa Cruz,42,NaN,NaN,"47°58'44""S 72°21'11""O",medio,"47°58'44""S","72°21'11""O",-47.978889,-72.353056
20,Lago Belgrano,Santa Cruz,42,NaN,NaN,"47°50'38""S 72°8'34""O",medio,"47°50'38""S","72°8'34""O",-47.843889,-72.142778
21,Lago Futalaufquen,Chubut,42,168.0,101.0,"42°49'42""S 71°40'31""O",medio,"42°49'42""S","71°40'31""O",-42.828333,-71.675278
22,Lago Posadas,Santa Cruz,41,NaN,31.0,"47°29'40""S 71°49'55""O",medio,"47°29'40""S","71°49'55""O",-47.494444,-71.831944
23,Lago Espejo,Neuquén,40,NaN,NaN,"40°40'33""S 71°42'40""O",medio,"40°40'33""S","71°42'40""O",-40.675833,-71.711111
24,Lago Mascardi,Río Negro,39,218.0,111.0,"41°20'46""S 71°32'52""O",medio,"41°20'46""S","71°32'52""O",-41.346111,-71.547778
25,Lago Chepelmut,"Tierra del Fuego, Antártida e Islas del Atlánt...",38,NaN,NaN,"54°23'42""S 67°35'36""O",medio,"54°23'42""S","67°35'36""O",-54.395000,-67.593333
26,Lago Salitroso o Sucio,Santa Cruz,37,NaN,NaN,"47°30'0""S 71°36'48""O",medio,"47°30'0""S","71°36'48""O",-47.500000,-71.613333
27,Lago Lolog,Neuquén,37,NaN,NaN,"40°2'10""S 71°32'11""O",medio,"40°2'10""S","71°32'11""O",-40.036111,-71.536389
28,Lago Tar,Santa Cruz,30,NaN,NaN,"49°13'42""S 72°1'2""O",medio,"49°13'42""S","72°1'2""O",-49.228333,-72.017222
29,Lago Tromen,Neuquén,29,NaN,69.0,"39°31'33""S 71°26'52""O",medio,"39°31'33""S","71°26'52""O",-39.525833,-71.447778
30,Lago Blanco,Chubut,28,NaN,NaN,"45°53'16""S 71°13'25""O",medio,"45°53'16""S","71°13'25""O",-45.887778,-71.223611
31,Lago Quillén,Neuquén,26,NaN,NaN,"39°24'41""S 71°18'52""O",medio,"39°24'41""S","71°18'52""O",-39.411389,-71.314444
32,Lago Asador o Guitarra,Santa Cruz,23,NaN,NaN,"47°51'45""S 71°28'13""O",medio,"47°51'45""S","71°28'13""O",-47.862500,-71.470278
33,Lago Rivadavia,Chubut,23,147.0,104.0,"42°36'39""S 71°39'59""O",medio,"42°36'39""S","71°39'59""O",-42.610833,-71.666389
34,Lago Moquehue,Neuquén,21,NaN,NaN,"38°54'16""S 71°16'26""O",medio,"38°54'16""S","71°16'26""O",-38.904444,-71.273889
35,Lago Correntoso,Neuquén,20,NaN,NaN,"40°42'8""S 71°39'35""O",medio,"40°42'8""S","71°39'35""O",-40.702222,-71.659722
36,Lago Río Chico,Chubut,20,NaN,NaN,"45°35'40""S 68°32'52""O",medio,"45°35'40""S","68°32'52""O",-45.594444,-68.547778
37,Lago Quiroga Chico,Santa Cruz,20,NaN,NaN,"48°29'57""S 71°35'5""O",medio,"48°29'57""S","71°35'5""O",-48.499167,-71.584722
38,Lago Epuyén,Chubut,17,148.0,92.0,"42°11'15""S 71°30'24""O",chico,"42°11'15""S","71°30'24""O",-42.187500,-71.506667
39,Lago Gutiérrez,Río Negro,17,111.0,80.0,"41°12'28""S 71°25'13""O",chico,"41°12'28""S","71°25'13""O",-41.207778,-71.420278
40,Lago Cholila,Chubut,17,108.0,49.0,"42°27'31""S 71°40'9""O",chico,"42°27'31""S","71°40'9""O",-42.458611,-71.669167
41,Lago Paimún,Neuquén,16,NaN,66.0,"39°43'27""S 71°35'2""O",chico,"39°43'27""S","71°35'2""O",-39.724167,-71.583889
42,Lago Azara,Santa Cruz,16,NaN,NaN,"47°50'45""S 72°16'13""O",chico,"47°50'45""S","72°16'13""O",-47.845833,-72.270278
43,Lago Burmeister,Santa Cruz,14,NaN,NaN,"47°57'20""S 72°12'9""O",chico,"47°57'20""S","72°12'9""O",-47.955556,-72.202500
44,Lago Onelli,Santa Cruz,14,NaN,NaN,"50°6'30""S 73°20'59""O",chico,"50°6'30""S","73°20'59""O",-50.108333,-73.349722
45,Lago Meliquina,Neuquén,14,NaN,NaN,"40°19'60""S 71°19'10""O",chico,"40°19'60""S","71°19'10""O",-40.333333,-71.319444
46,Lago Perito Moreno,Río Negro,12,NaN,NaN,"41°3'58""S 71°32'28""O",chico,"41°3'58""S","71°32'28""O",-41.066111,-71.541111
47,Lago Currhué,Neuquén,12,NaN,NaN,"39°50'24""S 71°30'27""O",chico,"39°50'24""S","71°30'27""O",-39.840000,-71.507500
48,Lago Falkner,Neuquén,11,NaN,NaN,"40°29'6""S 71°28'33""O",chico,"40°29'6""S","71°28'33""O",-40.485000,-71.475833
49,Lago Pico Nº 1,Chubut,10,NaN,NaN,"44°14'31""S 71°30'8""O",chico,"44°14'31""S","71°30'8""O",-44.241944,-71.502222
50,Lago Río Bueno,"Tierra del Fuego, Antártida e Islas del Atlánt...",10,NaN,NaN,"54°41'19""S 65°48'23""O",chico,"54°41'19""S","65°48'23""O",-54.688611,-65.806389
51,Lago Rosario,Chubut,10,57.0,25.0,"43°15'36""S 71°20'48""O",chico,"43°15'36""S","71°20'48""O",-43.260000,-71.346667

In [10]:
lagos[lagos["Ubicación"] == "Neuquén"]

,Nombre,Ubicación,Superficie (km²),Profundidad máxima (m),Profundidad media (m),Coordenadas,Sup Tamaño,Latitud en GMS,Longitud en GMS,Latitud en GD,Longitud en GD
9,Lago Huechulafquen,Neuquén,84,NaN,142.0,"39°46'28""S 71°30'32""O",grande,"39°46'28""S","71°30'32""O",-39.774444,-71.508889
10,Lago Traful,Neuquén,78,NaN,NaN,"40°37'50""S 71°24'55""O",grande,"40°37'50""S","71°24'55""O",-40.630556,-71.415278
14,Lago Aluminé,Neuquén,58,165.0,64.0,"38°55'18""S 71°7'35""O",medio,"38°55'18""S","71°7'35""O",-38.921667,-71.126389
15,Lago Lácar,Neuquén,53,277.0,166.0,"40°9'45""S 71°26'11""O",medio,"40°9'45""S","71°26'11""O",-40.162500,-71.436389
23,Lago Espejo,Neuquén,40,NaN,NaN,"40°40'33""S 71°42'40""O",medio,"40°40'33""S","71°42'40""O",-40.675833,-71.711111
27,Lago Lolog,Neuquén,37,NaN,NaN,"40°2'10""S 71°32'11""O",medio,"40°2'10""S","71°32'11""O",-40.036111,-71.536389
29,Lago Tromen,Neuquén,29,NaN,69.0,"39°31'33""S 71°26'52""O",medio,"39°31'33""S","71°26'52""O",-39.525833,-71.447778
31,Lago Quillén,Neuquén,26,NaN,NaN,"39°24'41""S 71°18'52""O",medio,"39°24'41""S","71°18'52""O",-39.411389,-71.314444
34,Lago Moquehue,Neuquén,21,NaN,NaN,"38°54'16""S 71°16'26""O",medio,"38°54'16""S","71°16'26""O",-38.904444,-71.273889
35,Lago Correntoso,Neuquén,20,NaN,NaN,"40°42'8""S 71°39'35""O",medio,"40°42'8""S","71°39'35""O",-40.702222,-71.659722
41,Lago Paimún,Neuquén,16,NaN,66.0,"39°43'27""S 71°35'2""O",chico,"39°43'27""S","71°35'2""O",-39.724167,-71.583889
45,Lago Meliquina,Neuquén,14,NaN,NaN,"40°19'60""S 71°19'10""O",chico,"40°19'60""S","71°19'10""O",-40.333333,-71.319444
47,Lago Currhué,Neuquén,12,NaN,NaN,"39°50'24""S 71°30'27""O",chico,"39°50'24""S","71°30'27""O",-39.840000,-71.507500
48,Lago Falkner,Neuquén,11,NaN,NaN,"40°29'6""S 71°28'33""O",chico,"40°29'6""S","71°28'33""O",-40.485000,-71.475833

Filtra los lagos de Chubut con superficie menor a 100 km²

In [19]:
p = lagos[lagos["Ubicación"] == "Chubut"]
p[p["Superficie (km²)"] < 100].value_counts()

Nombre             Ubicación  Superficie (km²)  Profundidad máxima (m)  Profundidad media (m)  Coordenadas            Sup Tamaño  Latitud en GMS  Longitud en GMS  Latitud en GD  Longitud en GD
Lago Menéndez      Chubut     58                287.0                   149.0                  42°41'28"S 71°51'45"O  medio       42°41'28"S      71°51'45"O       -42.691111     -71.862500        1
Lago Puelo         Chubut     47                180.0                   111.0                  42°9'3"S 71°38'59"O    medio       42°9'3"S        71°38'59"O       -42.150833     -71.649722        1
Lago Futalaufquen  Chubut     42                168.0                   101.0                  42°49'42"S 71°40'31"O  medio       42°49'42"S      71°40'31"O       -42.828333     -71.675278        1
Lago Rivadavia     Chubut     23                147.0                   104.0                  42°36'39"S 71°39'59"O  medio       42°36'39"S      71°39'59"O       -42.610833     -71.666389        1
Lago Epuyén        Chubut     17                148.0                   92.0                   42°11'15"S 71°30'24"O  chico       42°11'15"S      71°30'24"O       -42.187500     -71.506667        1
Lago Cholila       Chubut     17                108.0                   49.0                   42°27'31"S 71°40'9"O   chico       42°27'31"S      71°40'9"O        -42.458611     -71.669167        1
Lago Rosario       Chubut     10                57.0                    25.0                   43°15'36"S 71°20'48"O  chico       43°15'36"S      71°20'48"O       -43.260000     -71.346667        1
Name: count, dtype: int64

In [22]:
!pip install plotly

Collecting plotly
  Downloading plotly-6.8.0-py3-none-any.whl.metadata (9.0 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in /home/alumnos/taller/env/lib/python3.13/site-packages (from plotly) (25.0)
Downloading plotly-6.8.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 1.7 MB/s eta 0:00:00[36m0:00:01[36m0:00:01:01
Downloading narwhals-2.23.0-py3-none-any.whl (458 kB)
Installing collected packages: narwhals, plotly
Successfully installed narwhals-2.23.0 plotly-6.8.0

In [37]:
import plotly.express as px

3. Crea un gráfico que compare los porcentajes de lagos según la categoría de tamaño.

In [38]:
g = lagos["Sup Tamaño"].value_counts()
g

Sup Tamaño
medio     25
chico     14
grande    13
Name: count, dtype: int64

In [39]:
px.pie(data_frame = g, values = g.values, names = g.index, title = "").show()

In [10]:
mapa = generar_mapa()
mapa

In [4]:
import folium

In [5]:
def generar_mapa():
    attr = (
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> '
        'contributors, &copy; <a href="https://cartodb.com/attributions">CartoDB</a>'
    )
    
    tiles = 'https://wms.ign.gob.ar/geoserver/gwc/service/tms/1.0.0/capabaseargenmap@EPSG%3A3857@png/{z}/{x}/{-y}.png'
    m = folium.Map(
        location=(-33.457606, -65.346857),
        control_scale=True,
        zoom_start=5,
        name='es',
        tiles=tiles,
        attr=attr
    )
    return m

In [6]:
def agregar_marcar_lag(row):
    folium.Marker(
        [row['lat'], row['lng']],
        popup=row['Nombre'],
        icon=folium.Icon()
        ).add_to(mapa)